---

- name: Create filesystems
  filesystem:
    fstype: '{{ item.fstype }}'
    dev: '{{ item.src }}'
    resizefs: true
  with_items:
    - '{{ default_mounts }}'
    - '{{ custom_mounts }}'
  tags:
    - fs
    - disk
